// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI（db push / migrate）走直連。DATABASE_URL 是 pooled 連線，
    // 走 PgBouncer 交易模式執行 DDL 會失敗。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
